version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    image: network-policies-backend:latest
    container_name: backend
    environment:
      DB_CONN: host=db user=testuser password=testpass dbname=testdb sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    image: network-policies-frontend:latest
    container_name: frontend
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
